###
services:
  # https://hub.docker.com/_/traefik
  # https://docs.traefik.io/routing/providers/docker/
  traefik:
    image: traefik
    networks:
      - openland
    ports:
      - "${WEB_PORT:-80}:80"
      - "${ADMIN_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=openland"
      - "--providers.docker.constraints=Label(`custom.traefik.group`,`openaide`)"
      - "--entryPoints.web.address=:80"

  #
  whoami:
    image: traefik/whoami
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.whoami.rule=Host(`whoami.openaide.localhost`)
      - traefik.http.routers.whoami.entryPoints=web
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - custom.traefik.group=openaide

  # https://vercel.com/guides/does-vercel-support-docker-deployments
  home:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
      platforms:
        - linux/amd64
        - linux/arm64
    image: openaide/home
    restart: always
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.home.rule=Host(`home.openaide.localhost`)
      # - traefik.http.routers.home.rule=Host(`home.openaide.localhost`) || Host(`openaide.localhost`) || Host(`www.openaide.localhost`)
      - traefik.http.routers.home.entrypoints=web
      - traefik.http.services.home.loadbalancer.server.port=3000
      - custom.traefik.group=openaide

##
networks:
  # docker network create openland
  openland:
    external: true
###